name: Build site

on:
  push:
    branches:
    - master

jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Check out git repository
      uses: actions/checkout@v4

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'

    - name: Build CLI
      run: go build -o photoblog-go ./cmd/photoblog

    - name: Build site
      run: |
        ./photoblog-go

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: page
        FOLDER: public
        SINGLE_COMMIT: true
