name: Build site

on:
  push:
    branches:
    - master
env:
  CARGO_TERM_COLOR: always
  
jobs:
  build:
    name: build and deploy
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false

    steps:
    - name: Check out git repository
      uses: actions/checkout@v2

    - name: Build CLI
      run: cargo build --release

    - name: Build site
      run: |
        target/release/blog-cli

    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@releases/v3
      with:
        ACCESS_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        BRANCH: page
        FOLDER: public
        SINGLE_COMMIT: true
