name: Rust

on:
  push:
    branches:
      - master
env:
  CARGO_TERM_COLOR: always
  
jobs:
  release:
    name: build and release
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [windows-2019, macos-11, ubuntu-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@master

      - name: Build
        run: cargo build --release
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

      
      - name: upload artifacts
        uses: actions/upload-artifact@v3.0.0
        with:
          name: ${{ matrix.os }}
          path: target/release/blog-cli

      - name: release
        uses: softprops/action-gh-release@v0.1.14
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: "target/release/blog-cli"
        env:
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}
