name: Rust

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build-linux:

    runs-on: ubuntu-latest

    steps:
    - name: Build
      run: ls && cargo build --release
      
  build-windows:
    runs-on: windows-2019
    steps:
    - name: Build
      run: cargo build --release
      
  build-mac:
    runs-on: macos-11
    steps:
    - name: Build
      run: ls && cargo build --release
  
